-- Run this entire script in Supabase Dashboard -> SQL Editor.
create table if not exists public.signatures (
  id bigint generated by default as identity primary key,
  name text not null,
  department text not null,
  signature_data text not null,
  created_at timestamptz not null default now()
);

alter table public.signatures enable row level security;

-- Allow the public form to submit new signatures.
drop policy if exists "Public can submit signatures" on public.signatures;
create policy "Public can submit signatures"
on public.signatures
for insert
to anon
with check (
  length(trim(name)) between 1 and 200
  and length(trim(department)) between 1 and 200
  and length(signature_data) > 20
);

-- IMPORTANT: no SELECT policy is created.
-- This prevents anonymous visitors from reading submitted names/signatures.
